displayName=Live On Clan
author=Milico, Riven
description=Plugin oficial do clan Live On com comunicados, ranks, rankings MVP, lives e integração com o Discord
tags=clan,messages,announcements,ranks,twitch,mvp
version=1.2
plugins=com.liveon.ClanMessagesPlugin
build=standard
